/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_varcpq_Accounts_Payable_InvoiceTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_varcpq_Accounts_Payable_Ia0QTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new varcpq__Accounts_Payable_Invoice__c());
    }
}