/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Return_Merchandise_Authorizaa3QTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Return_Merchandise_Authora3QTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Return_Merchandise_Authorization_Line_It__c());
    }
}